### PR TITLE
added support for Neo4j subgraphs, closes #226

### LINKED ISSUE #226: Proposal for an add_graph_from_neo4j pull request
### Problem

There is currently no solution to display Neo4j graphs or the result of a Neo4j Cypher query (subgraph) in Jupyter Notebook.

### Proposed Solution

I can make a pull request for a`add_graph_from_neo4j `method that takes as input a Neo4j graph or subgraph.

### Additional context

This method would add a dependency on the py2neo library. Let me know if that's ok.

### PR DESCRIPTION
**Pull request by pwrose**
added add_graph_from_neo4j method to support rendering of Neo4j subgraphs. Added an example notebook.

### CODE REVIEW

**Comment by marimeireles** [comment]
>@marimeireles the tests are also trying to run Neo4j_Example.ipynb on binder, however, this will not work since binder blocks required ports. Can you exclude Neo4j_Example.ipynb from running on binder?

I'm not sure if I follow you here. 
The tests are run on an ubuntu, [here's](https://github.com/QuantStack/ipycytoscape/blob/master/.github/workflows/test.yml) the code for it.
We will definitely need to make some changes to the tests to cover your tests...

**Comment by pwrose** [comment]
The error message indicates that the Neo4j query returned no results. Perhaps run the notebook again once the code is checked in. It works fine when I run it locally.

**Comment by ianhi** [comment]
Hi @pwrose glad to see work on this progressing. Is it ready for review?

Also, you should be able to fix the lint issues by running `black .` from the terminal while in the ipycytoscape directory.

**Comment by pwrose** [comment]
I'm closing this pull request since I made some changes and improvements.

**Comment by pwrose** [comment]
Thanks for the tip about black. I’ll try to get this ready tomorrow and then you can review the code.

**Comment by pwrose** [comment]
@ianhi I've added a new pull request #245 that is ready for review. The lint test passes, but the other 3 tests fail. I'm not sure how to interpret the error messages and what needs to be fixed.

**Pull request closed without merging**
