### PR TITLE
fixes #125, pass the status of direction while creating edges

### LINKED ISSUE #125: Bug: Multiple edges between same nodes not shown
For a graph with edges 
A,B, weight=15
B,A, weight=10

Only the first edge object is retained in the  `add_edges(self, edges, directed=False)` method, which is wrong behaviour.

This `add_edges` method is used in `add_graph_from_networkx` method, which leads to deletion of certain edges from networkx graph.

image

### PR DESCRIPTION
**Pull request by MridulS**
We had a bug which prevented edges to be added in both directions in a Directed graph.

``` python
import networkx as nx
import ipycytoscape as ipc
G = nx.DiGraph()
G.add_edge(1,2,weight=15)
G.add_edge(2,1,weight=10)
cyto = ipc.CytoscapeWidget()
cyto.graph.add_graph_from_networkx(G, directed=True)
display(cyto)
```
The code above will now output something like 
Screenshot 2020-07-18 at 23 27 05

### CODE REVIEW

**Comment by ianhi** [comment]
What about also adding checks for the type of the networkx graph? If I have already created a `DiGraph` then I would not expect to need to add the `directed=True` argument. A way to get at maybe would be something at the start of function that does:

```python
if isinstance(graph, (nx.DiGraph, nx.MultiDiGraph)):
    directed = True
```

**Comment by ianhi** [comment]
@MridulS I left some comments on the higher level api decisions being made as that felt more natural. As a practical comment: can you please rebase on the master branch and then add test(s) for this?

**Comment by ianhi** [comment]
The relevant file is here: https://github.com/QuantStack/ipycytoscape/blob/master/ipycytoscape/tests/test_graph_creation.py

**Comment by MridulS** [comment]
@ianhi sorry for the delayed response on this! I have updated the graph creation test to test bidirections in a Directed Graph.  

I'll create a new PR for adding support for MultiGraphs (hopefully) in a couple of days :)

**Comment by ianhi** [comment]
> I'll create a new PR for adding support for MultiGraphs (hopefully) in a couple of days :)

I see we got this in a couple hours rather than a couple days! Is this then superseded by https://github.com/QuantStack/ipycytoscape/pull/146 or does it still make sense to merge?

**Comment by MridulS** [comment]
yeah this is superseded by #146, I'll close this :)

**Pull request closed without merging**
