### PR TITLE
Update postBuild to the latest lab extension

### PR DESCRIPTION
**Pull request by jtpio**
This should fix the lab issue on Binder.

### CODE REVIEW

**Comment by marimeireles** [comment]
Haha I was just making a PR for that, thanks Jeremy!

**Comment by maartenbreddels** [comment]
I was about to :-D

**Comment by jtpio** [comment]
We'll need to reset `stable` onto `master` so Binder can pick up this change.

**Comment by marimeireles** [comment]
Why doesn't binder get changes from master?

**Comment by jtpio** [comment]
That's because the link in the README uses the `stable` branch: https://mybinder.org/v2/gh/QuantStack/ipycytoscape/stable?filepath=examples

**Comment by jtpio** [comment]
But we can manually try on `master` with the following Binder link:

https://mybinder.org/v2/gh/QuantStack/ipycytoscape/master?filepath=examples

**Comment by marimeireles** [comment]
Oh! right. Thanks Jeremy, I'm gonna update it. Unless, you're already doing it. hehe

**Comment by jtpio** [comment]
Done :)

**Comment by marimeireles** [comment]
<3

**Pull request merged**
