### PR TITLE
Create initial python tests

### PR DESCRIPTION
**Pull request by ianhi**
I've never written tests from scratch before so I'm not sure if I'm approaching this correctly. Opening a PR early to test if I set up the travis file correctly

### CODE REVIEW

**Comment by ianhi** [comment]
Oh weird. The linux tests both passed but the macOS tests failed in confusing ways: 
image

I don't have access to mac to investigate that locally if anyone else does and could that would be rad

**Comment by marimeireles** [comment]
Will do!
Thanks for starting this! 🌸

**Comment by marimeireles** [comment]
Think the problem might be in these lines:
https://github.com/QuantStack/ipycytoscape/blob/122016dc0b65e12808f9d43c2b5034c0c9566155/.travis.yml#L27
specifying the OS. let's remove that & see

**Comment by marimeireles** [comment]
It's not that. The problem is that the notebook is not waiting for the cell finish its processing and it takes longer than 5 seconds.

```
_______________________________ examples/Tip gene example.ipynb::Cell 2 _______________________________
Notebook cell execution failed
Cell 2: Timeout of 5 seconds exceeded waiting for output.

Input:
cytoscapeobj = ipycytoscape.CytoscapeWidget()
cytoscapeobj.graph.add_graph_from_json(json_file)
cytoscapeobj.set_style(s)
```

I think the solution is to pass this flag: `jupyter nbconvert --NotebookClient.iopub_timeout : 10`, but I don't really know how to do that with pytest.

**Comment by marimeireles** [comment]
I tested this `pytest-timeout` and it doesn't work because of course it's not taking the cells of the notebook in consideration.
Hum, so I opened an issue in the `nbval` repo asking help for people. Cause I'm kind out of ideas, unless we start using `nbconvert`.

**Comment by marimeireles** [comment]
Just an organizational commit.
If you're interested in the `nbconver` architecture btw, here's an example using it: https://github.com/QuantStack/memestra/blob/master/tests/test_notebook.py
And the docs: https://nbconvert.readthedocs.io/en/latest/
But we can keep what you wrote, I like it. We just need to figure out this timing thing.

**Comment by ianhi** [comment]
One thing that's weird is that the linux notebooks don't time out. Maybe the mac infrastructure used by travis is a weaker computer and so each cell takes far longer to execute?

**Comment by ianhi** [comment]
We could also drop the mac tests if the problem is more so with test infrastructure than with ipycytoscape. To do that we could just adopt the cookiecutter travis file which is pretty different than ours: https://github.com/jupyter-widgets/widget-ts-cookiecutter/blob/master/%7B%7Bcookiecutter.github_project_name%7D%7D/.travis.yml

**Comment by ianhi** [comment]
Ok I don't that I fixed the original issue, I just sorta avoided it.... But I think it's reasonable to follow what the cookiecutter does anyway?

I think this is probably a good set of networkx tests. Although https://github.com/QuantStack/ipycytoscape/pull/126 would require adding a new test

Still need
- [ ] json graph creation
- [ ] df graph creation
- [ ] tests for `CytoscapeWidget` methods
- [ ] Tests of adding interaction callbacks 
    - will require using the mocked comms to fake a message. 

though for many of (all of?) those they could probably be split into a separate issue as it would be helpful to have networkx tests as that is what most PRs seem to concern.

**Comment by marimeireles** [comment]
>One thing that's weird is that the linux notebooks don't time out. Maybe the mac infrastructure used by travis is a weaker computer and so each cell takes far longer to execute?

Not sure if it's Travis' fault. The tests are also not passing on my PC.

> though for many of (all of?) those they could probably be split into a separate issue as it would be helpful to have networkx tests as that is what most PRs seem to concern.

Agreed.

I'm testing locally on my linux machine and found the following issues:

```
========================================================================== FAILURES ==========================================================================
_______________________________________________________________ TestNetworkx.test_lonely_nodes _______________________________________________________________

self = <ipycytoscape.tests.test_graph_creation.TestNetworkx object at 0x7f7fb39d7cd0>

    def test_lonely_nodes(self):
        """
        Test to ensure that nodes with no associated edges end up in the graph
        """
        G1 = nx.complete_graph(5)
        G2 = nx.Graph()
        G2.add_node('unconnected_node')
        G2 = nx.complete_graph(1)
        graph = Graph()
        graph.add_graph_from_networkx(G1)
        graph.add_graph_from_networkx(G2)
        expected_nodes = [
            Node(data={'id': '0'}, position={}),
            Node(data={'id': '1'}, position={}),
            Node(data={'id': '2'}, position={}),
            Node(data={'id': '3'}, position={}),
            Node(data={'id': '4'}, position={}),
            Node(data={'id': 'unconnected_node'}, position={})
            ]
        expected_edges = [
            Edge(data={'source': '0', 'target': '1'}, position={}),
            Edge(data={'source': '0', 'target': '2'}, position={}),
            Edge(data={'source': '0', 'target': '3'}, position={}),
            Edge(data={'source': '0', 'target': '4'}, position={}),
            Edge(data={'source': '1', 'target': '2'}, position={}),
            Edge(data={'source': '1', 'target': '3'}, position={}),
            Edge(data={'source': '1', 'target': '4'}, position={}),
            Edge(data={'source': '2', 'target': '3'}, position={}),
            Edge(data={'source': '2', 'target': '4'}, position={}),
            Edge(data={'source': '3', 'target': '4'}, position={})
        ]
>       compare_edges(expected_nodes, graph.nodes)

ipycytoscape/tests/test_graph_creation.py:57: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

expected_edges = [Node(data={'id': '0'}, position={}), Node(data={'id': '1'}, position={}), Node(data={'id': '2'}, position={}), Node(data={'id': '3'}, position={}), Node(data={'id': '4'}, position={}), Node(data={'id': 'unconnected_node'}, position={})]
actual_edges = [Node(data={'id': 0}, position={}), Node(data={'id': 1}, position={}), Node(data={'id': 2}, position={}), Node(data={'id': 3}, position={}), Node(data={'id': 4}, position={})]

    def compare_edges(expected_edges, actual_edges):
        for expected, actual in zip(expected_edges, actual_edges):
>           assert expected.data == actual.data
E           AssertionError: assert {'id': '0'} == {'id': 0}
E             Differing items:
E             {'id': '0'} != {'id': 0}
E             Full diff:
E             - {'id': 0}
E             + {'id': '0'}
E             ?        + +

ipycytoscape/tests/test_graph_creation.py:21: AssertionError
_______________________________________________________________ TestNetworkx.test_custom_node ________________________________________________________________

self = <ipycytoscape.tests.test_graph_creation.TestNetworkx object at 0x7f7fb3968400>

    def test_custom_node(self):
        class custom_node:
            def __init__(self, name):
                self.name = name
    
            def __str__(self):
                return "Node: " + str(self.name)
    
        n1 = custom_node("node 1")
        n2 = custom_node("node 2")
    
        G = nx.Graph()
        G.add_node(n1)
        G.add_node(n2)
        G.add_edge(n1, n2)
        graph =  Graph()
        graph.add_graph_from_networkx(G)
    
        expected_nodes = [
            Node(classes='', data={'id': 'Node: node 1'}, position={}),
            Node(classes='', data={'id': 'Node: node 2'}, position={})
        ]
        expected_edges = [
            Edge(data={'source': 'Node: node 1', 'target': 'Node: node 2'}, classes = '', position={})
        ]
    
>       compare_edges(expected_nodes, graph.nodes)

ipycytoscape/tests/test_graph_creation.py:130: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

expected_edges = [Node(data={'id': 'Node: node 1'}, position={}), Node(data={'id': 'Node: node 2'}, position={})]
actual_edges = [Node(data={'id': <ipycytoscape.tests.test_graph_creation.TestNetworkx.test_custom_node.<locals>.custom_node object at....tests.test_graph_creation.TestNetworkx.test_custom_node.<locals>.custom_node object at 0x7f7fb38468e0>}, position={})]

    def compare_edges(expected_edges, actual_edges):
        for expected, actual in zip(expected_edges, actual_edges):
>           assert expected.data == actual.data
E           AssertionError: assert {'id': 'Node: node 1'} == {'id': <ipycy...7f7fb38462b0>}
E             Differing items:
E             {'id': 'Node: node 1'} != {'id': <ipycytoscape.tests.test_graph_creation.TestNetworkx.test_custom_node.<locals>.custom_node object at 0x7f7fb38462b0>}
E             Full diff:
E             - {'id': <ipycytoscape.tests.test_graph_creation.TestNetworkx.test_custom_node.<locals>.custom_node object at 0x7f7fb38462b0>}
E             + {'id': 'Node: node 1'}

ipycytoscape/tests/test_graph_creation.py:21: AssertionError
_____________________________________________________________ TestNetworkx.test_subclassed_node ______________________________________________________________

self = <ipycytoscape.tests.test_graph_creation.TestNetworkx object at 0x7f7fb386c9a0>

    def test_subclassed_node(self):
        class CustomNode(Node):
            def __init__(self, name, classes='', custom_variable=1234):
                super().__init__()
                self.data['id'] = name
                self.classes = classes
                self.custom_variable = custom_variable
        n1 = CustomNode("node 1", classes='class1')
        n2 = CustomNode("node 2", classes='class2')
        G = nx.Graph()
        G.add_node(n1)
        G.add_node(n2)
        G.add_edge(n1, n2)
        graph = Graph()
        graph.add_graph_from_networkx(G)
    
        expected_nodes = [
            n1, n2
        ]
        expected_edges = [
            Edge(data={'source': 'node 1', 'target': 'node 2'}, classes = '', position={})
        ]
    
        for expected, actual in zip(expected_nodes, graph.nodes):
>           assert expected is actual
E           AssertionError: assert CustomNode(classes='class1', data={'id': 'node 1'}, position={}) is Node(data={'id': CustomNode(classes='class1', data={'id': 'node 1'}, position={})}, position={})

ipycytoscape/tests/test_graph_creation.py:157: AssertionError
====================================================================== warnings summary ======================================================================
/home/mariana/.local/lib/python3.8/site-packages/spectate/core.py:381
  /home/mariana/.local/lib/python3.8/site-packages/spectate/core.py:381: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    class Data(collections.Mapping):

/home/mariana/.conda/envs/ipycytoscape/lib/python3.8/site-packages/nbval/plugin.py:115: 12 tests with warnings
  /home/mariana/.conda/envs/ipycytoscape/lib/python3.8/site-packages/nbval/plugin.py:115: PytestDeprecationWarning: direct construction of IPyNbFile has been deprecated, please use IPyNbFile.from_parent
    return IPyNbFile(path, parent)

/home/mariana/.conda/envs/ipycytoscape/lib/python3.8/site-packages/nbval/plugin.py:311: 75 tests with warnings
  /home/mariana/.conda/envs/ipycytoscape/lib/python3.8/site-packages/nbval/plugin.py:311: PytestDeprecationWarning: direct construction of IPyNbCell has been deprecated, please use IPyNbCell.from_parent
    yield IPyNbCell('Cell ' + str(cell_num), self, cell_num,

examples/Cola example.ipynb::Cell 0
  /home/mariana/.local/lib/python3.8/site-packages/jupyter_client/manager.py:63: DeprecationWarning: KernelManager._kernel_spec_manager_changed is deprecated in traitlets 4.1: use @observe and @unobserve instead.
    def _kernel_spec_manager_changed(self):

-- Docs: https://docs.pytest.org/en/latest/warnings.html
================================================================== short test summary info ===================================================================
FAILED ipycytoscape/tests/test_graph_creation.py::TestNetworkx::test_lonely_nodes - AssertionError: assert {'id': '0'} == {'id': 0}
FAILED ipycytoscape/tests/test_graph_creation.py::TestNetworkx::test_custom_node - AssertionError: assert {'id': 'Node: node 1'} == {'id': <ipycy...7f7fb38...
FAILED ipycytoscape/tests/test_graph_creation.py::TestNetworkx::test_subclassed_node - AssertionError: assert CustomNode(classes='class1', data={'id': 'nod...
========================================================= 3 failed, 78 passed, 89 warnings in 18.90s =========================================================

```

So the first it's about types, I'm comparing a string with an int.
The second.. Is happening some weird stuff in here.
The third is asserting the wrong types.

But it works fine on travis, super weeeird :alien:

**Comment by ianhi** [comment]
I think thats because on travis it is including the changes from https://github.com/QuantStack/ipycytoscape/pull/118 but not locally because it was never explicitly rebased

**Comment by marimeireles** [comment]
I just rebased and did some trimming, if you have nothing else to add, we can merge :)
Damn, sorry for co authoring your commits :raccoon: 
It wasn't my intention, I shouldn't have force pushed D:

**Comment by ianhi** [comment]
>  if you have nothing else to add, we can merge :)

Rad - now we hopefully break the networkx methods slightly less often !

**Comment by marimeireles** [comment]
Yesss
Thanks Ian! :cherry_blossom:

**Pull request merged**
