### PR TITLE
Correct treatment of directed edges (isolated)

### PR DESCRIPTION
**Pull request by sven5s**
Like mentioned in #162 I separated the small patches from the rest to merge it as soon as possible.
Isolated test for this issue:
```
import ipycytoscape
data = {
    'nodes': [
        { 'data': { 'id': 'a'} },
        { 'data': { 'id': 'b'} }
    ],
    'edges': [
        {'data': { 'source': 'a', 'target': 'b' } }
    ]
}

graph = ipycytoscape.Graph()
graph.add_graph_from_json(data, directed=True)

graph.remove_edge(graph.edges[0])
```

### CODE REVIEW

**Comment by marimeireles** [comment]
Hey @sven5s, sorry for the delay. Was kinda giving all my energy on a different project, but now I'm back!
I revisited the last PR but can't make sense on why you're changing stuff from `==` to `in` without changing anything else. What does this imply in the behavior of ipycytoscape?
Thank you for sticking around and making a more bite sized PR! :cherry_blossom:

**Comment by sven5s** [comment]
This fixes the bug that was mentioned in my other PR. Previously the classes were changed to allow multiple classes but the comparison wasn't changed...
'in' allows to look for the occurrence of the string instead of a direct match. For a direct match 'directed' has to be changed to ' directed ' but then multiple classes are not easily usable.

**Comment by marimeireles** [comment]
Ah okay, I see.
Doesn't `classes` has to be a `MutableList` now?
https://github.com/QuantStack/ipycytoscape/blob/5508e30d4c71ce13c01bcd16c6962d4702cc03d0/ipycytoscape/cytoscape.py#L172
If we're using it to add different `string` classes: ` MutableList(Instance(Unicode())).tag(sync=True, **widget_serialization)` something like this?

**Comment by sven5s** [comment]
It would be an alternative but like mentioned in #162 this would break backward compatibility. Their are different possibilities to solve that in python and I want to evaluate with you the best solution in the other PR.

At the moment classes are added like this:
https://github.com/QuantStack/ipycytoscape/blob/5508e30d4c71ce13c01bcd16c6962d4702cc03d0/ipycytoscape/cytoscape.py#L320
but checked like this:
https://github.com/QuantStack/ipycytoscape/blob/5508e30d4c71ce13c01bcd16c6962d4702cc03d0/ipycytoscape/cytoscape.py#L428

This should be fixed with this small PR. Other things should be discussed in #162.

**Comment by marimeireles** [comment]
I'm sorry to make you repeat yourself @sven5s, thanks for explaining again.
So this example you added should be added to the tests?
(I can do it =) as well as rebase this)

**Comment by sven5s** [comment]
The rebase was a bit difficult because I use nbstripout and forget about it.

Maybe we should test add and remove for nodes and edges in general. My small snippet is a bit low. I will try to provide some tests if I'm able to set up the environment.

**Comment by marimeireles** [comment]
While writing tests you found the #191 ?
You think we should fix it before merging your changes here + adding tests?

**Comment by sven5s** [comment]
Yes, but #191 is not correlated to this one.
No, we should merge this and then continue with the other issues. I can also create a PR with my actual state of the tests if you want.

**Comment by marimeireles** [comment]
@sven5s I think it's better to post the tests relevant to these changes here, in the same PR.
Or do you mean you're creating more tests? If you are I think it'd be better to split.

**Comment by sven5s** [comment]
I want to write test for the whole remove and add methods of the graph class. The part for the remove-methods for edges and nodes is finished for all three different kind of graphs (default, directed, multiple_edges). But during this I encountered the issue. I can split in multiple files if you want. But like networkx I want to combine all tests in one file.

**Comment by ianhi** [comment]
I'm going to close and re-open to try to pick up the updated CI on github actions

**Review by ianhi — APPROVED** [review]
This is a good fix and it would be to have included in the next release https://github.com/QuantStack/ipycytoscape/issues/209 so I think we merge now and include the tests for this when more complete tests get written.

Thanks @sven5s !

**Comment by ianhi** [comment]
> I separated the small patches from the rest to merge it as soon as possible.

We don't seem to have actually made a release since September which is the real limiting factor on getting this out there. I'd like to make one soon that will include this (see https://github.com/QuantStack/ipycytoscape/issues/209)

**Pull request merged**
