### PR TITLE
Remove postBuild entirely: Compliment of Issue #235

### PR DESCRIPTION
**Pull request by sandertyu**
This the the PR with my suggested changes to `postBuild` as shown in issue #235.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
I am not sure we need to build lab in post-script since we moved to pre-built extensions with JupyterLab 3.0.

**Comment by ianhi** [comment]
> I am not sure we need to build lab in post-script since we moved to pre-built extensions with JupyterLab 3.0.

It was necessary/nice as the default `jupyter-offlinenotebook` was still prompting users for a build, but I believe that that has been resolved. 


@sandertyu thank you for the PR. Would you mind modifying your PR to entirely remove the `postBuild` entirely?

**Comment by sandertyu** [comment]
I've removed `postBuild` from my PR, but jupyter-offlinenotebook is still requesting a rebuild of jupyterlab;

extension-list

**Comment by ianhi** [comment]
How are you making that binder? For me the version based off of this branch does not prompt me to build. You can see here: https://mybinder.org/v2/gh/LibreTexts/ipycytoscape/reduce-postBuild?urlpath=lab/tree/examples

**Comment by sandertyu** [comment]
> How are you making that binder? For me the version based off of this branch does not prompt me to build. You can see here: https://mybinder.org/v2/gh/LibreTexts/ipycytoscape/reduce-postBuild?urlpath=lab/tree/examples

You're right, I see the same behavior now. I was testing on a binderhub which was pinned to an out of date version of repo2docker. I see that it works with no issues after `postBuild` now as well.

**Comment by marimeireles** [comment]
So I'll be merging it :)
Thanks everybody!

**Pull request merged**
