### PR TITLE
add jupyter lab build to test

### PR DESCRIPTION
**Pull request by ianhi**

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks!

Maybe it could also be useful to add the browser check?

**Comment by ianhi** [comment]
Good call will do. Also, what does that browser check actually do? i.e. what does it check?

**Comment by jtpio** [comment]
It uses puppeteer to access JupyterLab and check there is not JS or Python errors.

**Comment by ianhi** [comment]
So the tests passed but it really looks as though should not have due to an error in browser_check: https://travis-ci.com/github/QuantStack/ipycytoscape/jobs/367744428#L580-L600
Shouldn't these tests fail if browser_check fails like that?
image

**Comment by marimeireles** [comment]
Hey @ianhi Jeremy is out for vacations.
So, we're getting a `name 'time' isn't defined` here.
What if
we do something like:
https://github.com/jupyterlab/extension-cookiecutter-ts/blob/cb9ca8c37bf1c5c28be61b31e6fcd0cf60487a5f/.github/workflows/main.yml#L45-L46

**Comment by ianhi** [comment]
> So, we're getting a name 'time' isn't defined here.
What if

So I think this was fixed upstream and should be released at some point ([ref](https://github.com/jupyterlab/jupyterlab/blob/f65c1c65bcb156acfe75b6f2144887a19c59175a/jupyterlab/browser_check.py#L15)). My concern is more so that for some reason our tests didn't fail even though the browser check failed :thinking:

**Comment by marimeireles** [comment]
Interesting! Thanks for the update @ianhi.
Yes that's a good question, so, we have to keep this in mind I think, and retry it when a new version is released.

**Comment by ianhi** [comment]
Per https://github.com/jupyterlab/jupyterlab/issues/8752#issue-671072621 
> Note: the exception is silenced as it happens after the test succeeds.

So I think that my concern above is not actually an issue

**Comment by marimeireles** [comment]
Hum, we're getting a new error here:
```
[E 14:56:52.056 BrowserApp] Uncaught exception GET /foo/lab/api/settings/?1597762611663 (127.0.0.1)

    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/foo/lab/api/settings/?1597762611663', version='HTTP/1.1', remote_ip='127.0.0.1')

    Traceback (most recent call last):

      File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/tornado/web.py", line 1703, in _execute

        result = await result

    tornado.iostream.StreamClosedError: Stream is closed
```
But I don't think it concern us at all, since we don't even have this dependency in ipycytoscape. I'm going to merge it as the browser test passed and the other jupyter bug disappeared.

**Pull request merged**
