### PR TITLE
Lazy loading lab, distribute more files

### PR DESCRIPTION
**Pull request by bollwyvl**
Thanks for this publishing this repo!

This PR is just some tweaks to packaging:
- change the generated module type to be `esnext` so that it can...
- move the the loading of the widget (and its dependencies) to be lazy loaded when a widget is actually requested
  - sizes
    - in production, this is 600kb
    - in development, this is 5mb
  - seems like not too much, in the face of a 5/35mb bundle, but if every library adds another 0.5mb, end users start getting out-of-memory errors :crying_cat_face: 
- add the source maps, typings and license files to the distribution
  - for When Things Break

### CODE REVIEW

**Comment by marimeireles** [comment]
Hey @bollwyvl thanks a lot for this PR :)
I'll just rebase because we had a lil bit of refactoring here.

**Comment by SylvainCorlay** [comment]
Nice to see you here @bollwyvl!

**Comment by marimeireles** [comment]
JS contributions are **super** welcome, btw :)
Thanks a lot 🌸

**Comment by bollwyvl** [comment]
Hooray!

**Pull request merged**
