### PR TITLE
chore: automate having mybinder files up to date

### PR DESCRIPTION
**Pull request by maartenbreddels**
This automates replacing the version numbers in the mybinder files.
This uses the _version.py file as truth, maybe you also want an action in the task to update the json file and have a git hook?

### CODE REVIEW

**Comment by marimeireles** [comment]
Thanks PR @maartenbreddels! :) 
I don't know how to use github actions, I just have to add something like this:

```
 pip install doit
 doit
```

To the config of github actions?

What do you mean with son file?

**Comment by maartenbreddels** [comment]
No GHA required, if you run this locally with `doit`, it will make sure your binder files are up to date.
You can try:
 * pip install doit
 * modify _version.py
 * run `$ doit`
 * see the changes
 * enjoy life 😄

**Comment by marimeireles** [comment]
Haha seems good!

I thought you meant I should integrate it with GHA when you said 

> maybe you also want an action in the task to update the son file and have a git hook?

What did you mean here? Sorry :p

**Comment by maartenbreddels** [comment]
> update the son file

A very aggressive spell corrector, should have been json.

What i meant is that you can have a git hook execute this locally before you commit, so it's always up to date. And in the file, you see 1 task with 1 action, but it can also have another action, which is to update the son.

 feel free not to merge this, only if you like it, I'm just putting it out there for inspiration.

**Comment by marimeireles** [comment]
Not at all. I'm interested in merging it, just wanted to understand if I'd have to make any extra changes here.

Thanks a lot for the script <3

**Pull request merged**
