### PR TITLE
add black formatting

### PR DESCRIPTION
**Pull request by CagtayFabry**
in case #165 is still relevant, here is a small PR with black formatting applied (with a simple GitHub action to check)

I added `pyproject.toml` to simplify configuration since single quote strings seem to be used throughout the project (unless you want to switch to double quotes)

### CODE REVIEW

**Comment by marimeireles** [comment]
Hey @CagtayFabry, yeah! Still super relevant. Thank you for adding this!

> I added pyproject.toml to simplify configuration since single quote strings seem to be used throughout the project (unless you want to switch to double quotes)

I try not to have strong opinions about formatting haha
Whatever is the default thing I think we should go with it, I'm happy with single quotes, but if you think double is more widely used, would be okay too. :) What do you think it's best?

I think once you've answered we can merge this, what do you think @ianhi?
Thanks again for the contribution! :cherry_blossom:

**Comment by CagtayFabry** [comment]
> Hey @CagtayFabry, yeah! Still super relevant. Thank you for adding this!
> 
> > I added pyproject.toml to simplify configuration since single quote strings seem to be used throughout the project (unless you want to switch to double quotes)
> 
> I try not to have strong opinions about formatting haha
> Whatever is the default thing I think we should go with it, I'm happy with single quotes, but if you think double is more widely used, would be okay too. :) What do you think it's best?
> 
> I think once you've answered we can merge this, what do you think @ianhi?
> Thanks again for the contribution! 🌸

I have updated the PR to use default black formatting (meaning double quote strings), which does blow up the diff a bit ..

In the tiny Python bubble I tend to live in I think double quotes are more common, but please don't quote me :wink:
Regardless, if you don't have any strong preferences in this regard going with the black defaults seems like a good choice, just run `black .` in the root directory and you should be fine without tinkering with any settings

Merge as you wish or just ping me if you want me to go back to single quote strings

**Comment by marimeireles** [comment]
>   @marimeireles I have updated the PR to use default black formatting (meaning double quote strings), which does blow up the diff a bit ..

It's totally fine. Thanks a lot @CagtayFabry ! :)

**Comment by ianhi** [comment]
nice thanks! Two easy followups that we may want to do someday:
1. Add instructions on using black to https://ipycytoscape.readthedocs.io/en/latest/contributing.html
2. add `61c0fd86367b4ecfdb348826af5adae33d34203a` to a `.git-blame-ignore-revs` file

**Comment by marimeireles** [comment]
Great input :)

**Pull request merged**
