### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by ianhi**
close: https://github.com/QuantStack/ipycytoscape/issues/65

- Added linting plus styling with eslint and prettier
   - pretty much copied all the lint/prettier settings from jupyterlab-git minus the react stuff in that repo
- I gave the typescript version a fairly large bump to get eslint run without complaining (to 3.7.1)
- ran `npm run lint` to apply linting changes
    - Some of the changes are definitely subjective choices that can clash with the previously used style. But this way there will be easily enforced consistency from all contributors. If anything is particularly troublesome I'll bet we could find a way to change the rules to fix it. 

I didn't add this as a check to be run on PRs because there are some errors regarding the use of `require` that I don't feel qualified to deal with. Specifically:

```
> jupyter-cytoscape@0.2.2 lint /home/ian/Documents/jupyter/ipycytoscape
> eslint . --ext .ts --fix


/home/ian/Documents/jupyter/ipycytoscape/src/extension.ts
  12:3  warning  Forbidden non-null assertion  @typescript-eslint/no-non-null-assertion

/home/ian/Documents/jupyter/ipycytoscape/src/version.ts
  4:14  error  Require statement not part of import statement  @typescript-eslint/no-var-requires

/home/ian/Documents/jupyter/ipycytoscape/src/widget.ts
   12:17  error    Require statement not part of import statement  @typescript-eslint/no-var-requires
  344:33  error    Expected '!==' and instead saw '!='             eqeqeq
  383:15  warning  Forbidden non-null assertion                    @typescript-eslint/no-non-null-assertion
  383:15  warning  Forbidden non-null assertion                    @typescript-eslint/no-non-null-assertion

✖ 6 problems (3 errors, 3 warnings)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jupyter-cytoscape@0.2.2 lint: `eslint . --ext .ts --fix`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jupyter-cytoscape@0.2.2 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ian/.npm/_logs/2020-05-07T00_04_32_624Z-debug.log
```
note that the no-var-requires can be ignored with a rule

### CODE REVIEW

**Comment by ianhi** [comment]
One of the builds got weirdly stuck. Don't know whats up with that, but there is also a passing build in those details.

I avoided the remaining lint errors by adding two single line ignore the rule statements:
```typescript
// eslint-disable-next-line @typescript-eslint/no-var-requires
```

then there were no remaining lint errors so I added `npm run lint-check` to .travis.yml

The two new commands in package.json are:
`npm run lint` which will try to automatically fix errors
and `npm run lint-check` which will not fix the errors.

It is also set up so that when you run `git add` the staged files are checked for lint errors.

**Comment by marimeireles** [comment]
Hey @ianhi 
Apparently it's some problem with the linter. I'm not familiar with it, but I'll try to give a look on it later.
```
/home/travis/build/QuantStack/ipycytoscape/src/extension.ts

  12:3  warning  Forbidden non-null assertion  @typescript-eslint/no-non-null-assertion

/home/travis/build/QuantStack/ipycytoscape/src/widget.ts

  388:15  warning  Forbidden non-null assertion  @typescript-eslint/no-non-null-assertion

  388:15  warning  Forbidden non-null assertion  @typescript-eslint/no-non-nul
```

Thank you very much for the PR :)

**Comment by ianhi** [comment]
now warning free™

reading this link helped me figure out what was going on: https://palantir.github.io/tslint/rules/no-non-null-assertion/

**Comment by marimeireles** [comment]
> ran npm run lint to apply linting changes 

I think I'm doing something wrong?
When I run `npm run lint` it doesn't happen anything. Just this:

```
> jupyter-cytoscape@0.2.2 lint /Users/mariana/Development/jupyter-ecosystem/test/ipycytoscape
> eslint . --ext .ts --fix
```

I installed it with npm. Is there some extra step?
According to your comments, not all is linted, right?

Thanks a lot :)

**Comment by ianhi** [comment]
I ended up fixing everything it complained about after I learned a little more about what the errors meant and consequently decreased my fear of breaking things. 

I get the same output as well now. Try editing `widget.ts` to muck up the indentation and then run`npm run lint-check` and it should tell you the error. After that if you run `npm run lint` then the error will be fixed in the file.

**Comment by marimeireles** [comment]
Oh wow! :D
Thanks a lot <3
I will and if it's all working will merge it right away, thank you very much for your work here.

**Comment by marimeireles** [comment]
Did you try to run any example with your changes? 
It broke for me, but it might be because of some other stuff going on in my local env. It's a bit late today, but I'll keep looking tomorrow :)
Thanks again!

**Comment by ianhi** [comment]
Oh dang. All the examples I test behaved as I expected, which ones broke for you? It's definitely possible they were broken in ways I didn't realize. 


>  It's a bit late today, but I'll keep looking tomorrow :)

Sure thing, I'm in no rush. Better to get it right than just get it done.

**Comment by marimeireles** [comment]
Just retested everything in a clean env. and I was wrong.
This works perfectly.
Thank you very much for your work @ianhi! :)

**Pull request merged**
