### PR TITLE
Tooltips on edges

### PR DESCRIPTION
**Pull request by ngthanhvinh**
I've modified the code so that the `set_tooltip_source` also works for edges now. Could you please review it?

### CODE REVIEW

**Comment by marimeireles** [comment]
Thank you for the PR and for creating an example to test it. 
I think this example "Tooltips on edges" might be a bit too specific, but I think it'd be cool to have a tooltip only example, what do you think? If it's okay, can you please rename it to tooltip example?
And also a nitpicking, could you clean the notebook cells, you just have to click on "Restart and clear output", so we have an uniform clean notebook :)
image
Other than that it works fine for me and I think we can merge it. Anything to add @ianhi?

**Comment by ianhi** [comment]
>  Other than that it works fine for me and I think we can merge it. Anything to add @ianhi?

I agree with everything you said - only other thing is to please make sure the interaction example still works and the existing tooltip examples do not break.

**Comment by ngthanhvinh** [comment]
I've updated the PR. Could you check it again please? Thanks in advance!

**Comment by ianhi** [comment]
Awesome thanks. Though just one more thing: it looks as though a yarn.lock snuck in in the latest commit. can you remove that? I think this SO post will show you the commands: https://stackoverflow.com/questions/12481639/remove-files-from-git-commit

```
git reset --soft HEAD~1
git reset HEAD yarn.lock
# commit
```

**Comment by ngthanhvinh** [comment]
I removed the yarn.lock from the commit, but the code failed. I am not sure of what happened. Could you please check on that?

**Comment by ianhi** [comment]
I also am not sure what happened there. I think we can chalk that one up to a travis error as all the other builds passed and the only check that actually happens in the js group is a lint check (we should also ensure that `jupyter lab build` will work). Also none of your changes should have caused that error so I'm gonna merge it and then open a new PR to check that the build passes. 

Thanks for the fix!

**Comment by marimeireles** [comment]
If the problem was just rerun the tests you can do that in the Travis CI interface without having to open a new PR to trigger them.
You just have to search a bit it's in a sub menu.

**Pull request merged**
