### PR TITLE
adding cyto_from_scratch_example & method to add class to a node by id

### PR DESCRIPTION
**Pull request by joseberlines**
Dear Mariana,
Dear Ianhi,

I added an example called cyto_from_scratch_1

The intention is to create a notebook that enables users to understand graphs from scratch using ipycytoscape. 
All the data is self contain: i.e. there is no JSON external file to read. 
I tried to explain ipycytoscape as if the one reading only knows python, no idea about JS, CSS, or whatever else.
This is a problem colleagues of mine are encoutering.

That said when I have time I will go for the cyto_from_scratch_2 in which I will deal with other issues that I mention at the end of the notebook itself.

Please bear in mind that this is my first ever pull request in GitHub. Tell me if I still have to do something extra.

Well let me know if you accept the example and otherwise how can I modify it.

cheers.

### CODE REVIEW

**Comment by joseberlines** [comment]
Dear Mariana,
Dear Ianhi,

I added a method in the main ipycytoscape code that adds a class to a node by using the id of the node.
It raises error if the node does not exists (to be considered to skip error if the id is lower/upper case or not)
if the node exists It looks for the node with the name passed (to be considered passing a class to several nodes-> list)
a set of classes is added i.e. no repetition of classes will occur.

Note: as mentioned before those two are my first pull requests. I would like to have made the request separately but I was not able. I don't even know if it is possible.

Cheers.
Jose Ferro

def add_class_to_node_by_id(self,node_id,classes_to_add):
        """
        __by Jose Ferro__ -> line to be deleted
        Add a class to a node. equivalent to append to a set of classes.
        Parameters
        ----------
        self: cytoscape graph
        node: cytoscape node
        classes_to_add: a single string or a list of strings
        """

**Comment by marimeireles** [comment]
Ok @joseberlines 
Sorry for the delay on answering this. My advice if that you close this PR and we open a new one, it's good to compartmentalize things. Here are some git tips that are not only useful for this project, but to all.

First you want to have a remote for you (called origin) and one with the upstream changes (the main repo).

```
git remote add upstream  git@github.com:QuantStack/ipycytoscape.git
```

Now make sure everything is updated:

```
git pull upstream master
git push origin master
```

Now create a new branch for one kind of change you're making with a short name that has smth to do with the content of this branch:

```
git checkout -b add-new-notebook
```

Make your changes in modular commits, write a commit message that summarize your changes, and `git add` them to your branch.

Once all your changes are done, push it to your remote and specify this newly created branch:

```
git push origin add-new-notebook
```

Use github's interface to open a PR in the upstream.

And that's it basically :)

If you want to fix merging issues, like the ones you're having in this PR you'll have to deal with rebase:

```
git checkout master
git pull upstream master
git push origin master
git checkout your-branch
git rebase -i master
```

And fix the conflicts, but as I said, I recommend opening two new PRs. If you face any issue while doing this git stuff let me know on: https://gitter.im/marimeireles

If you're not up to doing all these changes I could grab your PR and do it for you and mark you as an author.
Thanks for all the work! :)
Cheers

**Comment by marimeireles** [comment]
Just so I don't forget, the first commit -regarding the notebook- usually we use the option "clean all cells", so there's no output from any cell and the numbers of operation in the cells are empty.

**Comment by joseberlines** [comment]
Ok, I will cancel the PR and will do as you say.
So forget about the this PR.
I am really busy today and tomorrow.
I will come back Wendesday

**Pull request closed without merging**
